- evmlab/compiler.py
- reproduce.py
Run with 
```
./reproduce.py 0x9dbf0326a03a2a3719c27be4fa69aacc9857fd231a8d9dcaede4bb083def75ec
```
To test attack transaction and generate trace. Trace files are not saved inside working directory.
> make txhash argument, clean up code, add calldata forwarding to boostrap code

- evmlab/gethvm.py
- evmlab/parityvm.py
Docker containers persist after exiting, so they accumulate and take up disk space unless cleaned up.
> use --rm flag to clean up docker containers after exit

- containers/buildandpushall.sh
- containers/cpp-ethereum/Dockerfile
- containers/pyethereum/Dockerfile
- containers/pyethereum/run_statetest.py
- containers/std-cpp-ethereum/Dockerfile
- containers/std-geth/Dockerfile
- containers/std-parity/Dockerfile
- evmlab/genesis.py
- evmlab/gethvm.py
- evmlab/opcodes.py
- statetests.ini
- trace_statetests.py
Work-in-progress, don't merge.
Docker images for standardized tracing (https://github.com/ethereum/tests/issues/249) install these branches:
https://github.com/cdetrio/parity/tree/evmlab-trace
https://github.com/cdetrio/cpp-ethereum/tree/evmlab-trace
https://github.com/cdetrio/go-ethereum/tree/evmlab-trace
https://github.com/cdetrio/pyethereum/tree/evmlab-trace
```
cd containers/std-cpp-ethereum && docker build --no-cache . -t cdetrio/cpp-ethereum
cd containers/std-parity && docker build --no-cache . -t cdetrio/parity
cd containers/std-geth && docker build --no-cache . -t cdetrio/geth
cd containers/pyethereum && docker build --no-cache . -t cdetrio/pyethereum
```
> [WIP] StateTest tracer using docker images for parity, cpp, geth

- containers/pyethereum/run_statetest.py
- evmlab/vm.py
- statetests.ini
- trace_statetests.py
Fixes an error:
```
2017-09-10 15:51:03,578 - INFO - file: /ethereum/tests/GeneralStateTests/stCallCreateCallCodeTest/createNameRegistratorPerTxsNotEnoughGas.json, test name createNameRegistratorPerTxsNotEnoughGas 
Setting prestate to homestead config
2017-09-10 15:51:03,578 - INFO - prestate: {'env': {'currentCoinbase': '0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba', 'currentDifficulty': '0x20000', 'currentGasLimit': '0x02540be400', 'currentNumber': '0x01', 'currentTimestamp': '0x03e8', 'previousHash': '0x5e20a0453cecd065ea59c37ac63e079ee08998b6045136a8ce6635c7912ec0b6'}, 'pre': {'0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b': {'balance': '0x0de0b6b3a7640000', 'code': '', 'nonce': '0x00', 'storage': {}}}, 'config': {'metropolisBlock': 2000, 'eip158Block': 2000, 'eip150Block': 2000, …
```
> compare state roots at end of trace

- evmlab/vm.py
fixes #20 
tmp files created on osx are created under /var/folders/...
/var on osx is a symlink to /private/var. In order to mount the genesis
file so the docker image can see it, we need to specifiy the destination
path of the symlink.
> mount /var as private on OSX docker run cmd

- trace_statetests_new.py
On my machine, the next iteration was overwriting the current test tmpfile before both clients had finished reading and executing. Using unique tmpfile filenames fixes it.
> Fix race writing to tmpfile 

- evmlab/source_map.py
- opviewer.py
I think I got this about 80% working, but it jumps around to the wrong position after the first instructions so there must be some bugs still there. Perhaps you or someone else can pick up from here. Let me know if you have more luck.
You can call it like this:
```
python opviewer.py -f output/0x5e76b2_vbmcwt8q.txt \
-j combined_json.json \
-s BurnableToken.sol \
-c BurnableToken.sol:BurnableToken
```
And press `p` to print the replace the trace panel with source code.
> [WIP] Add initial support for Solidity source maps

- evmlab/context.py
- evmlab/contract.py
- evmlab/opcodes.py
- evmlab/reproduce.py
- evmlab/utils.py
- opviewer.py
- reproducer.py
* builds upon PR #31 
This PR adds a window in `opviewer.py` that displays the source code of the current op.
Notable changes:
1. `opviewer.py` - if given a txHash and a `combined.json` file, will display the sourcecode.
2. `opviewer.py` - will now call `reproducer` if a file is not passed in. This is more of a convenience thing. I figured it was easier then running 2 separate cmds & I needed to add `--web3`, `--hash` to the opviewer anyways.
3. `reproducer.py` - remove default `www` value as this caused the webapp to always run if flask was installed
TODO:
I have tested on a few different contract transactions & deployments, and it seems to work correctly. 
The window could be better & highlight the current code in the contract. Currently I surround the current code with `**code**`.
> add sources to opviewer

- evmlab/context.py
- evmlab/contract.py
- evmlab/opcodes.py
- opviewer.py
improves upon the initial source view implementation...
fixes a bug where the same contract is displayed for a given depth. The previous code assumed that depth to contract was a 1-1 mapping. This is not correct. In the scenario where A calls B, returns, then calls C, both B & C are at depth 1 but are different contracts.
fixes a bug with multi-contract files. The previous code assumed the contract we want to display was always the first in the file. We now use a regex and a loop to pull the currently executing contract out of the file
improves visibility of currently executing code. The current code is now highlighted in monochrome bold instead of being surrounded by `**`, improving readability
> improve source code view

- containers/std-parity/Dockerfile
- containers/testeth/Dockerfile
- evmlab/vm.py
- statetests.ini
- trace_statetests_new.py
This PR updates `trace_statetests_new.py` to operate on semi-persistent docker containers. 
- Each testcase runs as basically `docker exec -it <name> <args>` instead of spinning up a new container every time
- Instead of using `subprocess`, it's using `docker-py` to communicate with docker directly. This makes the thing more robust
> Experimental containers

- opviewer.py
Added memory inspection to fulfill #35 - currently it's selectable if you press "SHIFT" and drag the mouse around, and it has normal ternimal text-copy behaviour. urwid doesn't seem to support "smart selection". Perhaps could make it so that if the user presses "m" the current memory inspection window is saved to a file?
I've also added support for showing memory referenced by a PREVIOUS opcode, in case the opcode is e.g. CALLDATACOPY and the user wants to see the resulting effect of that opcode on the memory area.
Screenshots:
[current opcode view](https://i.imgur.com/ZSTC7sL.png)
[prev opcode view](https://i.imgur.com/apiVYVZ.png)
> Memory inspection feature #35

- statetests.ini
- trace_statetests_new.py
Adds this capability to `trace_statetests_new.py`.  It appears there may have been some changes applied that broke this feature.  I wasn't able to get it working with the older script: `trace_state_tests.py`.
> Add the ability to run trace equivalence tests on existing state test suite

- README.md
It would seem that the intent was to give the user a shell to execute the supplied examples or their own cases. I am by no means a docker expert but this seems to be the correct way to do so
> Use docker interactive and tty flag when running image

- evmlab/genesis.py
PR to enable constantinople on the evms. Missing skinny create2 for parity (see also https://github.com/karalabe/hive/pull/114 )
> Update genesis factory to support constantinople

- evmlab/vm.py
- utilities/fuzzer.py
This fixes the remaining snags about parity stateroot problems. I've been running it locally without hitting any false positives for a few minutes, seems to work ok
> fix parity stateroot problem

- utilities/fuzzer.py
Fixes the following problem when temp is on a separate filesystem from where artefacts are stored:
```
Traceback (most recent call last):
File "utilities/fuzzerweb.py", line 59, in <module>
main()
File "utilities/fuzzerweb.py", line 55, in main
f.startFuzzing()
File "/datadrive/evmlab/utilities/fuzzer.py", line 467, in startFuzzing
__end_previous_test()
File "/datadrive/evmlab/utilities/fuzzer.py", line 441, in __end_previous_test
failingTestcase = processTraces(previous_test)
File "/datadrive/evmlab/utilities/fuzzer.py", line 410, in processTraces
test.saveArtefacts()
File "/datadrive/evmlab/utilities/fuzzer.py", line 165, in saveArtefacts
os.rename(self.fullfilename() , saveloc)
OSError: [Errno 18] Invalid cross-device link: '/datadrive/evmlabtemp/testfiles/DEFAULT-Wed_07_15_02-17565-118 …
```
> fuzzer: use shutil.move instead of os.rename

- evmlab/tools/opviewer.py
- evmlab/tools/statetests/rndval/__init__.py
- setup.py
Added `ethereum-dasm` to **extra dependency** `fuzztests` required for smart-code generation. This extra dependency should list all depdendencies explicitly required for the fuzztests.
```
#> (.env3) tin@ubuntu1610:~/evmlab$ pip install -e ".[fuzztests]"
```
```
(.env3) tin@ubuntu1610:~/evmlab$ pip install "evmlab[fuzztests]"
```
If everything works out it should not show the following warning: `----> Falling back to Random Code Generation based on byte distribution!`
> Fix/smart code generation dependency 

- evmlab/tools/statetests/templates/object_based.py
avoid creating invalid transactions by not generating random values for transactions or we might end up with lots of transactions sending more value than available in the account.
as per request @holiman / discord.
>(MHS) Should rather always be between zero and <whatever that account has in the prestate
> fix - do not generate random transaction values to avoid creating invalid transactions that attempt to spend more than the accounts balance

- evmlab/tools/statetests/templates/object_based.py
update to #72 that hardcoded the value to zero. changed it to randomly generated balance (same for all prestates) but never spend more than what is in the accounts balance
fixes #70
> fix high rate of non-executable statetests

- evmlab/opcodes.py
- evmlab/tools/opviewer.py
- evmlab/tools/statetests/rndval/__init__.py
- evmlab/tools/statetests/rndval/address.py
- evmlab/tools/statetests/rndval/codesmart.py
- evmlab/tools/statetests/templates/object_based.py
- evmlab/vm.py
- utilities/fuzzer.py
- utilities/test_minimizer.py
I investigated why traces were so short, and found and fixed a lot of errors.. 
- ethereum-dasm incorrectly padded with zeroes after certain ops, like `MSTORE`: https://github.com/tintinweb/ethereum-dasm/pull/9 
- Transaction-create never happened
- The address type used `to_bytes`, which fell back to the super object, which always returned random bytes. 
- Many ops were using too large memory areas for their operands. 
Also, instructions were incorrectly generating code with this construct:
```
instructions = [asm_registry.create_instruction(opcode=opcode) for opcode in self.random_code_byte_sequence(self.length)]
```
Using `self.length` instead of `length`. This caused the size of generated code to blow up something humongous.
> More fixes

- evmlab/vm.py
- sstore_fun.py
- utilities/fuzzer.py
Fixes https://github.com/ethereum/evmlab/issues/90 , by deleting files after a run. 
Also shortens the stack output in `toText`. Any consensus issues in the earlier part of the stack will be visible later or sooner, when the stack is shallower again. 
Also added an example to repro the constantinople fork.
> clean up after run

- README.md
deduplicating information shown in the `Readme.md` as we already moved it to an easier digestible structure in the [Wiki](https://github.com/ethereum/evmlab/wiki) 
refs #60
> shorten readme and direct to wiki

- evmlab/genesis.py
Parity genesis format expects a non zero networkID. Fixes #100.
> fix parity genesis config

- evmlab/tools/statetests/rndval/__init__.py
- evmlab/tools/statetests/rndval/codesmart2.py
- setup.py
* https://github.com/tintinweb/evmdasm is now the central registry for instructions. it also provides disassembly manipulation functionality
* https://github.com/tintinweb/evmcodegen creates random evmcode and is based on evmdasm. it is split up in a generator part (generate code based on byte/instr/custom distribution) and a generic interface to generate evmcode.
* evmcodegen has not yet been published to pypi and needs to be installed before it can be used
* evmcodegen is missing some manipulation code (bitflipping, instr insertion, corruption, etc)
**dont merge yet**
> use RndCode2 based on evmcodegen and evmdasm

- utilities/fuzzer.py
I've quickly refactored `fuzzer.py`. no original code was omitted. Most of the methods are now part of the new `Fuzzer()` class (together with `TestExecution` the entry class for fuzzing. see `def main`)
once this is merged we can easily add new configurative options (like evmcodegen selection, etc.) (see #91)
**the --config option is mandatory**
```
python utilities/fuzzer.py -c statetests.ini
```
**usage**
```
python utilities/fuzzer.py --help
usage: fuzzer.py [-h] [-v VERBOSITY] -c CONFIGFILE [-x] [-r]
Ethereum consensus fuzzer
optional arguments:
-h, --help            show this help message and exit
-v VERBOSITY, --verbosity VERBOSITY
available loglevels:
critical,fatal,error,warning,warn,info,debug,notset
-c CONFIGFILE, --configfile CONFIGFILE
path to configuration file (default: …
```
> refactor fuzzer.py for reusability and prepare cmdline/ini config merging

- evmlab/tools/statetests/randomtest.py
- evmlab/tools/statetests/rndval/__init__.py
- evmlab/tools/statetests/rndval/base.py
- evmlab/tools/statetests/rndval/code.py
- evmlab/tools/statetests/rndval/codesmart.py
- evmlab/tools/statetests/rndval/codesmart2.py
- evmlab/tools/statetests/templates/statetest.py
- statetests.ini
- utilities/fuzzer.py
// this is a preparation to make various settings configurable via cmdline/statetests.ini. There's no good way to achieve this using the current dictionary approach. Wit the object we can implement measures that make sure to always create syntactically correct statetests to minimize errors and tune performance
* switch from dictionary based templates to a concrete statetest objects (gives better control over random code genration and allows optimizations for speed, type of code generated, etc)
* track addresses that have been generated and autofill prestates for used state accounts
* collect more stats: avg trace length, max trance length, % of zero length traces
* do not always generate new values (xmas fuzzing)
* we now have easy control over what type of codegenerators to use
* added …
> create consistent StateTestTemplate object instead of dict

- containers/testeth/Dockerfile
- evmlab/tools/statetests/rndval/address.py
- evmlab/tools/statetests/rndval/codesmart.py
- evmlab/tools/statetests/templates/statetest.py
- utilities/fuzzer.py
This PR fixes some bugs I ran into trying to get it to work with the legacy code generators, and also has some improvements. 
* The fuzzer now does not create/delete files all the time , but instead overwrites old files using a pooled approach. 
* The fuzzer now makes testcases that are create-transactions. 
* The spurious failures #102 is fixed, we simply ignore it if it happens. 
* Added back the old prestate accounts, they had gone missing if we weren't using the smart analyzer to figure out which accounts were used. 
@tintinweb I probably screwed up with your code, sorry
> use pooled files, enable create, make old code generator work
